name: daily
on:
  schedule: [{ cron: '0 6 * * *' }]   # every day 06:00 UTC
  workflow_dispatch:
permissions: { contents: write }
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - name: Seed + Build site
        run: |
          python -m src.eval.seed_db
          python -m src.publish.build_site
      - name: Copy site to /docs for Pages
        run: |
          rm -rf docs || true
          mkdir -p docs
          cp -R site/public/* docs/
      - name: Commit site
        run: |
          git config user.name "cornerpro-bot"
          git config user.email "bot@cornerpro"
          git add docs || true
          git commit -m "daily publish" || true
          git push
