name: daily
on:
  schedule: [{ cron: "0 6 * * *" }]  # 06:00 UTC daily
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily job
        run: bash jobs/daily.sh

      - name: Commit site & data
        run: |
          git config user.name "cornerpro-bot"
          git config user.email "bot@cornerpro"
          git add docs data/processed site/public
          git commit -m "daily: ingest + score + publish" || echo "nothing to commit"

      - name: Push
        run: git push
